name: Notificar a Discord

on: push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"📦 Push detectado en *${{ github.repository }}* por *${{ github.actor }}* en la rama *${{ github.ref }}*\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
